### ISSUE TITLE
WeaponUpgrades: upgrading damage seems to makes nobelisks powerful enough to wipe out big chunks of the map

### ISSUE THREAD

**Issue by Kadigan** [PiggyChu620/SatisfactoryMods#1]
For some reason, nobelisks are affected very badly - or seem to be. I tried leaving nobelisk power be, upgrading only "regular" weapon damage - but it seems not to work. I can't use nobelisks, because they end up killing me unless I move to another biome before detonating one.

What can I do/what can I check to give you a better idea of what's going on with my setup?

**Comment by PiggyChu620** [comment]
Please come join us at https://discord.gg/hSBmVCXPN6
